### ISSUE TITLE
[UNINSTALLATION]Cannot uninstall WSA Sideloader from Microsoft Store.

### ISSUE THREAD

**Issue by FurryBoyYT** [infinitepower18/WSA-Sideloader#104]
### Describe the bug

I want to uninstall wsa sideloader that i installed from microsoft store but i couldn't find the uninstall button!
Can anyone help me?

### Steps to reproduce

Not sure what this means.

### Expected behavior

Uninstalling

### Download source

Microsoft Store

### WSA version

2309.40000.10.0

### WSA Sideloader version

1.4.4

### Windows build number

22623.1250

**Comment by infinitepower18** [comment]
Right click the app on the start menu and select uninstall.

**Comment by FurryBoyYT** [comment]
> Right click the app on the start menu and select uninstall.

Ah yes, thank you very much!
