### ISSUE TITLE
[BUG] "list index out of range" error after clicking on Open app button

### ISSUE THREAD

**Issue by asyncButNeverAwaits** [infinitepower18/WSA-Sideloader#114]
### Describe the bug

![image](https://github.com/infinitepower18/WSA-Sideloader/assets/111964298/0c28a9bd-057a-4b25-bd35-63900a6ae8cb)

### Steps to reproduce

1. Install app
2. Click on Open app button
3. Error

### Expected behavior

Able to open app

### Download source

Microsoft Store

### WSA version

2311.40000.5.0

### WSA Sideloader version

1.4.4

### Windows build number

22621.3296

**Comment by infinitepower18** [comment]
Very strange, I never encountered this. Could you please let me know the following info:

- System language
- x64 or ARM64
- Whether you are running an original or modified version of Windows

Also what happens if you press continue?

**Comment by infinitepower18** [comment]
Do you have the APK file for me to test?

**Comment by asyncButNeverAwaits** [comment]
> Do you have the APK file for me to test?

From what I tested, it should due to apk filename that containing Chinese character

Steps:
1. Download any app e.g. https://apkpure.com/notepad-notes/com.eco.note/download
2. Rename downloaded apk file to contain Chinese character
e.g.
Rename `Notes - Notebook, Notepad_1.9.83_Apkpure.apk` to `Notes - Notebook, Notepad_1.9.83_Apkpure - 中文.apk`
3. Install app
4. Click on Open app button
5. Error

**Comment by infinitepower18** [comment]
The program uses aapt to get the package name as well as the list of permissions, it seems it doesn't work with Chinese characters:

<img width="867" alt="image" src="https://github.com/infinitepower18/WSA-Sideloader/assets/44692189/0f5366aa-22ae-4ae5-aa79-aa2222da185e">

For now, I would advise to rename the file before using "Open app" or attempting to view permissions for APK files. XAPK, APKM and APKS files don't seem to be affected by this.

**Comment by asyncButNeverAwaits** [comment]
noted. Thank you.
