### ISSUE TITLE
Can not upgrade Amazon KINDLE app [BUG]

### ISSUE THREAD

**Issue by rjsq00** [infinitepower18/WSA-Sideloader#118]
### Describe the bug

When I try to upgrade KINDLE application with the WSA sideloader, I get tis error:

INSTALL_FAILED_DUPLICATE_PERMISSION:  Package com.amazon.kindle attempting to redeclare permission android.permission.ACCESS_ALL_DOWNLOADS already owned by com.android.providers.downloads

### Steps to reproduce

Upgrade kindle to level 14.98.100 (2.0.11694.0)

### Expected behavior

Can install the update.  I have been doing so for over a year.

### Download source

Microsoft Store

### WSA version

2311.40000.5.0

### WSA Sideloader version

1.4.5

### Windows build number

22631.3527

**Comment by rjsq00** [comment]
Are you saying there is a newer version of WSA?  Where do I get it?Sent from my iPhoneOn May 1, 2024, at 12:59 PM, Ahnaf Mahmud ***@***.***> wrote:﻿
Closed #118 as completed.

**Comment by infinitepower18** [comment]
I meant you need to delete the Kindle app from WSA and install the latest version of the app. Also, WSA has been discontinued by Microsoft so there won't be any more updates to WSA itself. https://github.com/microsoft/WSA/discussions/536

**Comment by rjsq00** [comment]
Okay thank you.  I will try that.Sent from my iPhoneOn May 1, 2024, at 3:03 PM, Ahnaf Mahmud ***@***.***> wrote:﻿
I meant you need to delete the Kindle app from WSA and install the latest version of the app. Also, WSA has been discontinued by Microsoft so there won't be any more updates to WSA itself. microsoft/WSA#536

**Comment by rjsq00** [comment]
Same error after deleting it and restarting WSA.  The older 8.99 version of kindle installs and works fine.  Disappointing that Microsoft is dropping support for WSA.

Regards,
Robert Scardapane
________________________________

**Comment by infinitepower18** [comment]
Possibly there is something with the APK that WSA is not liking. Where did you download it from?

From what I heard, WSA was discontinued as they rely on Microsoft Store revenue to fund development but the revenue wasn't sufficient enought to continue it.

**Comment by rjsq00** [comment]
I was using APKPURE.  I got tired of that environment and tried BLUESTACKS out.  It seems to be working better.  Given that MS is deprecating WSA I might as well get away from it.Thx for your responsesSent from my iPhoneOn May 2, 2024, at 4:54 PM, Ahnaf Mahmud ***@***.***> wrote:﻿
Possibly there is something with the APK that WSA is not liking. Where did you download it from?
From what I heard, WSA was discontinued as they rely on Microsoft Store revenue to fund development but the revenue wasn't sufficient enought to continue it.
