### ISSUE TITLE
[BUG] installing error

### ISSUE THREAD

**Issue by TimucinPusat** [infinitepower18/WSA-Sideloader#125]
### Describe the bug

I installed an app using sideloader and then tried to install another one but it says: 

Sorry, an error has occured. Please submit a bug report
[Error Info]
list index out of range

it is an arabic dictionary I don't know if it's the reason but the first app also contains arabic words. 

### Steps to reproduce

.

### Expected behavior

.

### Download source

Microsoft Store

### WSA version

.

### WSA Sideloader version

.

### Windows build number

.

### Additional context

.

**Comment by TimucinPusat** [comment]
after removing arabic letters from app's name it worked.

**Comment by infinitepower18** [comment]
Did this happen when trying to install an APK? Most likely it's adb/aapt which this program relies on which has issues with such characters.
