### ISSUE TITLE
Unable to install APK.

### ISSUE THREAD

**Issue by Silence374** [infinitepower18/WSA-Sideloader#126]
### Describe the bug

No connection could be made because the target machine refused it.
I am assuming this is a bug.

### Steps to reproduce

Clicked browse and clicked the file then clicked install.

### Expected behavior

To start downloading the APK.

### Download source

Microsoft Store

### WSA version

2311.40000.5.0

### WSA Sideloader version

1.4.5

### Windows build number

22631.3880

### Additional context

Developer mode was on.

**Comment by infinitepower18** [comment]
This is a [bug](https://github.com/microsoft/WSA/issues/136) with the subsystem itself, restarting the PC will usually fix it.

If you still get this error, try these steps:

1. Make sure WSA is turned off and disable WSA autostart in Task Manager, startup apps before proceeding with the below steps

2. Disable Hyper-V using the command dism.exe /Online /Disable-Feature:Microsoft-Hyper-V and reboot your PC

3. Reserve port 58526 so Hyper-V doesn't reserve it back using the command netsh int ipv4 add excludedportrange protocol=tcp startport=58526 numberofports=1

4. Re-enable Hyper-V using the command dism.exe /Online /Enable-Feature:Microsoft-Hyper-V /All and reboot your PC
