### ISSUE TITLE
[BUG] WSA-S fails to install APK: `INSTALL_PARSE_FAILED_NO_CERTIFICATES`

### ISSUE THREAD

**Issue by davidedpg10** [infinitepower18/WSA-Sideloader#128]
### Describe the bug

Not entirely sure if it's a bug or intended behavior, but I'm trying to install a game using an APK I downloaded from [APK Combo](https://apkcombo.com/last-horizon/com.noodlecake.lasthorizon/), I followed the instructions on this repo, enabled `Developer Mode`, ensured the ADB connection address was right, I even disabled `Block installation of malicious apps` in the `System` settings, but I'm unable to get past this error.

### Steps to reproduce

- Downloaded [apk](https://apkcombo.com/last-horizon/com.noodlecake.lasthorizon/) from APKCombo, 
- Attempted to install it using WSA Sideloader
- - Observed error
Error:
```
[Error Info]
Performing Streamed Install
adb: failed to install \\?\C:\Users\porti\Downloads\Last
Horizon_1.1.0_apkcombo.com.apk: Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES:
Scanning Failed .: No signature found in package of version 2 or newer for
package com.noodlecake.lasthorizon]
```
![image](https://github.com/user-attachments/assets/e102a4a5-2459-4f0a-86df-8415d2c27e3f)

### Expected behavior

Successful installation of app

### Download source

Microsoft Store

### WSA version

2311.40000.5.0

### WSA Sideloader version

1.4.5 

### Windows build number

22631.3880

**Comment by Jazhet** [comment]
no me agrada mucho

**Comment by infinitepower18** [comment]
Looks like a problem with the APK itself: https://stackoverflow.com/questions/2914105/what-is-install-parse-failed-no-certificates-error

Are you able to install other APKs without issue?
