### ISSUE TITLE
Suface Pro 11 không chạy được App Android trên Windown 11

### ISSUE THREAD

**Issue by LyDucCanh** [infinitepower18/WSA-Sideloader#141]
### Describe the bug

Tôi đã thủ rất nhiều cách nhưng không thể chạy được ứng dụng Anroid,
Hãy giúp tôi, xin cảm ơn!

### Steps to reproduce

![App Android](https://github.com/user-attachments/assets/a5822f55-d940-4c77-84ab-5b03120890a2)

### Expected behavior

Chạy được các ứng dụng Androi trên CHPlay, Amazone....

### Download source

Microsoft Store

### WSA version

Tích hợp sẵn trên Windown 11

### WSA Sideloader version

Mới nhất

### Windows build number

Windows 11 Home Insider Preview. Evaluation copy. Build 27729.rs_prerelease.241011-1428

**Comment by infinitepower18** [comment]
Did you enable developer mode in WSA settings?

If you did and you still get this, then this is a [bug](https://github.com/microsoft/WSA/issues/136) with the subsystem itself. Restarting the PC will usually fix it.

If you still get this error, try these steps:

1. Make sure WSA is turned off and disable WSA autostart in Task Manager, startup apps before proceeding with the below steps

2. Disable Hyper-V using the command `dism.exe /Online /Disable-Feature:Microsoft-Hyper-V` and reboot your PC

3. Reserve port 58526 so Hyper-V doesn't reserve it back using the command `netsh int ipv4 add excludedportrange protocol=tcp startport=58526 numberofports=1`

4. Re-enable Hyper-V using the command `dism.exe /Online /Enable-Feature:Microsoft-Hyper-V /All` and reboot your PC

You are also running a preview version of Windows 11, and as Microsoft is no longer supporting WSA, you might run into problems.
