### ISSUE TITLE
[BUG] Device offline

### ISSUE THREAD

**Issue by Err0rC0rrupt** [infinitepower18/WSA-Sideloader#62]
### Describe the bug

When opening WSA with Gapps, it is unable to connect to port 127.0.0.1:58526 and says adb.exe: device offline, while installing Nova Launcher that worked before this change.

### Steps to reproduce

Follow WSAGAScript/README.md on GitHub, and install Nova Launcher 8.0.3 beta (arm64-v8a + arm-v7a) (Android 8.0+) from APKMirror. (first link)

### Expected behaviour

It should've just installed it, but it outputted the following error:
![Screenshot (4)](https://user-images.githubusercontent.com/118559056/218284979-b4c3bf38-5b9b-4509-b7ac-42f029d9b167.png)

### Download source

Microsoft Store

### Application version

1.3.10

### Windows build number

Windows 11 22H2 (22621.1105) (Home)

### Additional context

I have WSL working and I have an x86_x64 Intel i5 processor, with GTX 1650 as GPU.

**Comment by infinitepower18** [comment]
Hmm it's probably the WSA itself acting weird with the adb connection. Could you open a PowerShell window and run the following commands:

`C:\Users\[username]\AppData\Local\Packages\46954GamenologyMedia.WSASideloader-APKInstaller_cjpp7y4c11e3w\LocalState\platform-tools` replace the [username] with your Windows account name

`.\adb connect 127.0.0.1:58526`

And provide the output here.

**Comment by Err0rC0rrupt** [comment]
New error: 
![Screenshot (5)](https://user-images.githubusercontent.com/118559056/218354337-44bc1d5d-6adc-4519-9f9b-58419dacb457.png)

**Comment by Err0rC0rrupt** [comment]
The output in terminal was: already connected to 127.0.0.1:58526

**Comment by Err0rC0rrupt** [comment]
I just chickened out and removed OpenGapps from WSA, sorry.
