### ISSUE TITLE
[BUG] IP address error

### ISSUE THREAD

**Issue by skullcrushercmd** [infinitepower18/WSA-Sideloader#67]
### Describe the bug

when the app auto detects the ip, it isn't using the right one, instead of using the IP of the computer it should be using 127.0.number number or smth like that with the port, and the dev option in the subsystem app needs to be enabled rather than dev in system settings.

### Steps to reproduce

simply trying to install something 

### Expected behavior

should work rather then refusing to connect (bc of wrong IP)

### Download source

Microsoft Store

### WSA version

from ms

### WSA Sideloader version

should not matter, newest version

### Windows build number

some beta of windows 11

**Comment by skullcrushercmd** [comment]
never mind ab the dev options, but the auto detect IP should be changed

**Comment by infinitepower18** [comment]
Do you have a screenshot of the error info?

The app does not auto detect the IP, it uses 127.0.0.1:58526 by default unless you modify the ADB address field in case WSA settings shows a different IP (which seems very unlikely). 127.0.0.1 is the IP address for the local machine.

**Comment by infinitepower18** [comment]
As I haven't heard from you in a while, I will be closing this issue. I have just released version 1.3.13 which fixes one bug. If you're still encountering problems, do let me know.

**Comment by skullcrushercmd** [comment]
yeah, i was wrong
