### ISSUE TITLE
Sideload folders/files

### ISSUE THREAD

**Issue by ghost** [infinitepower18/WSA-Sideloader#78]
### Describe your request

Integrate 'adb  push' to allow easy side-loading of folders/files in addition to apk's.

**Comment by NebularNerd** [comment]
The latest versions of WSA are going to allow mapping your user directory as a faux SD Card which will be cool for sideloading and adding content. [https://www.theregister.com/2023/06/13/microsoft_windows_files_android/](https://www.theregister.com/2023/06/13/microsoft_windows_files_android/)

**Comment by roshan308** [comment]
I m getting error in adb conection after installind adb also

**Comment by infinitepower18** [comment]
@roshan308 Please open a new GitHub issue with screenshot of the error info, operating system and whether you are using the official WSA or a community build so I can help you further.
